######################################################################
# Automatically generated by qmake (3.1) Fri Jul 28 15:04:03 2017
######################################################################

TEMPLATE = app
TARGET = jsonedit
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    jsonview.cpp \
    jsonmodel.cpp

QT += widgets

HEADERS += \
    jsonview.h \
    jsonmodel.h
